http:
  host: 'localhost'
  port: 8080
db:
  postgres:
    synchronize: true
    dropSchema: false
hash:
  salt: 10
  file_salt: 'U12Dwci01lqE'
token:
  access_token_expires: '1h'
  refresh_token_expires: '1d'
support:
  active: true
file:
  upload_path: './uploads'
dev:
  create: false
  full_name: 'Super Admin'
  username: 'super_admin'
  password: 'SuperAdmin#123'

external_systems:
  hemis_base_url: 'https://hstudent.nuu.uz'

