export enum ErrorsEnum {
  USERNAME_OR_PASSWORD_INVALID_EXCEPTION,
  USER_IS_BLOCKED_EXCEPTION,
  INVALID_REFRESH_TOKEN,
  USER_ALREADY_EXIST_WIDTH_USERNAME_EXCEPTION,
  USER_NOT_FOUND_EXCEPTION,
  FILE_NOT_UPLOADED,
  FILE_NOT_FOUND,
  SOCIAL_LINK_ALREADY_EXIST_EXCEPTION,
  EMPLOYER_ALREADY_EXIST_EXCEPTION,
  EMPLOYER_NOT_FOUND_EXCEPTION,
  SOCIAL_LINK_NOT_FOUND_EXCEPTION,
}
